<?php
    include'utils.inc.php';
    //Correspondàl’adresseIPdeceluiquivisualiselapage.
    echogetenv('REMOTE_ADDR');
    //Correspondàl’adresseIPduserveur.
    echogetenv('HTTP_HOST');//Correspondau
    //logicielserveurWebutilisé.
    echogetenv('SERVER_SOFTWARE');
    phpinfo();
?>